apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sp-tst-29jan-gitops
  description: This is GitOps manifest for sp-tst-29jan   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: sp-tst-29jan
    backstage.io/kubernetes-id: sp-tst-29jan 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: sp-tst-29jan   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:sp-tst-29jan
