apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sp-tst-29jan
  janus-idp.io/tekton: sp-tst-29jan
  backstage.io/kubernetes-id: sp-tst-29jan
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sp-tst-29jan
resources:
- deployment.yaml
- route.yaml
- service.yaml
