apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: sp-tst-29jan
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sp-tst-29jan 
  name: sp-tst-29jan
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: sp-tst-29jan
    weight: 100 
