apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sp-tst-29jan
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sp-tst-29jan 
  name: sp-tst-29jan
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sp-tst-29jan 
